### ISSUE TITLE
A url can set multiple router handler if it matches?

### ISSUE THREAD

**Issue by Neojoke** [button/DeepLinkKit#102]
What can i do if i want make a url pass by multiple router handler?  A router handler can pass openURL request to another router handler？

**Comment by chrismaddern** [comment]
Hey @Neojoke! Would love to understand what you're trying to achieve to be able to map it best to either what DLK does today, or figure out a requirement for the future.

**Comment by Neojoke** [comment]
For example,I want to open a UIViewController which was wrapped by UITabBarController in my app,I use a url like "app://tabBarController_selectedIndex/viewController_name" to represent this action,I set a router handler like this:
```
//first call back
_router[@"tabBarController_selectedIndex"] = ^(DPLDeepLink * link){
        [_tabBarViewController setSelectedIndex:3];
    };
//second call back
_router[@"/viewController_name"] = [SubClassDPLRouteHandler Class];

```
If app receive a url like "app://tabBarController_selectedIndex/viewController_name",first call back doesn't pass through,second call can match.
Although DLK can set multiple routers to realize this , if DLK can give DPLDeepLinkRouter forward request of ability, it will be great!

**Comment by Neojoke** [comment]
Like this:
```
//first call back
_router[@"tabBarController_selectedIndex"] = ^BOOL(DPLDeepLink * link){
        [_tabBarViewController setSelectedIndex:3];
        return YES;
    };
//second call back
_router[@"/viewController_name"] = [SubClassDPLRouteHandler Class];
```
Return a Bool to decide to send next router call back if have another call back matched.
