### ISSUE TITLE
 Registering routes for url

### ISSUE THREAD

**Issue by DinaHussieny** [button/DeepLinkKit#108]
I try to registering routes for this url [http://www.mydomain.com/compare?ids=12345,67891](url)
I register it as
router[@"http://www.mydomain.com/compare?ids=:firstID,:secondID"] = ^() {}
but it always gives me The passed URL does not match a registered route

**Comment by platedbay** [comment]
You don't register query parameters in routes. Instead, just register the route as `/compare` and when you handle the `DPLDeepLink`, you'll be given access to the query parameters via the `deepLink.queryParams` dictionary.
