### ISSUE TITLE
Xcode 8.3 beta compilation fails

### ISSUE THREAD

**Issue by taher-mosbah** [button/DeepLinkKit#119]
On Xcode 8.3 beta (8W109m) compilation fails with the following error : 
`redefinition of module 'DeepLinkKit' `

not sure if it is a DeepLinkKit issue or a Cocoapods issue ..

**Comment by taher-mosbah** [comment]
@seanjsummers deleting the content of the file "fixed" the problem for me.

**Comment by ranganathagv** [comment]
If you just want to run you can comment that file content and run, but not sure how functionally it breaks

**Comment by salabaha** [comment]
https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html

**Known Issues**
When building a framework that has module maps in both the source and the install directories that define the same module, the compiler will show a redefinition message. (28638816)
**Workaround:** Rename the module map file in the source directory to a non-default name (the default name is module.modulemap or module.map), and set the Module Map File build setting to the renamed module map.

**Comment by igor-makarov** [comment]
I suggest specifying the public and private headers in the podspec and getting rid of the manually defined module map altogether. 

[Link to relevant chapter in the Podspec docs](https://guides.cocoapods.org/syntax/podspec.html#public_header_files)

**Comment by Ekhoo** [comment]
Any chance to release a fix ?

**Comment by igor-makarov** [comment]
My PR [#121](https://github.com/button/DeepLinkKit/pull/121) fixes that.

**Comment by Unihilator** [comment]
can't wait to merge it guys

**Comment by Ekhoo** [comment]
👍

**Comment by igor-makarov** [comment]
My PR got merged. @chrismaddern can you please tag out a new release for @taher-mosbah @superpeteblaze @Ekhoo who are waiting for it in this thread.

**Comment by platedbay** [comment]
Definitely excited for this to roll out too, just a friendly reminder that you can point your source to a specific commit/branch if you don't want to wait around for a new release and subsequent pod update (if using cocoapods). We've been doing this to keep development rolling.

**Comment by igor-makarov** [comment]
Yeah, I've got my Podfile pointed at my fork for a couple of days @platedbay

**Comment by chrismaddern** [comment]
@wessmith  will be shipping a new version today @igor-makarov 😄

**Comment by wessmith** [comment]
Closed in #121 and part of [1.2.2](https://github.com/button/DeepLinkKit/releases/tag/1.2.2)

**Comment by igor-makarov** [comment]
BTW all tests are passing but Slather can't find the coverage output, so Coveralls isn't updated. I don't know enough about those tools to fix it 😂 @chrismaddern @wessmith

**Comment by Unihilator** [comment]
New arrives after a fix. But probably it's only mine.

`../DebugTest-iphonesimulator/DeepLinkKit/DeepLinkKit.framework/Modules/module.modulemap:2:19: Umbrella header 'DeepLinkKit-umbrella.h' not found`

**Comment by igor-makarov** [comment]
@unihilator Well, since now the module map is auto generated, it's a CP issue...

**Comment by Unihilator** [comment]
Probably.. removed workspace and pod dir. updated pods - and now it's ok
