### ISSUE TITLE
Can I use this library in my Swift 3 project?

### ISSUE THREAD

**Issue by MarksCode** [button/DeepLinkKit#124]
I see this is written in Obj-C and all the documentation is in Obj-C. Does anybody know if there are swift 3 API's for this library? If not does anybody recommend any other libraries?

**Comment by chrismaddern** [comment]
Hey @MarksCode -- DeepLinkKit will indeed work just fine with Swift 3 -- infact we released 1.2.2 to ensure Xcode 8.3 / Swift 3 compatibility -- https://github.com/button/DeepLinkKit/releases/tag/1.2.2.

We're working on some Swift interface improvements for the future -- would welcome any and all P/Rs ranging from docs to improvements you'd like to see.
