### ISSUE TITLE
Matching regex paths

### ISSUE THREAD

**Issue by jbrennan** [button/DeepLinkKit#126]
Hello! I am trying to match a regular expression-based URL but I’m having trouble getting the syntax right. I want to match something like this:

```
/*/open/*
```

That is, the path accepts something like `/user/open/account` (any path, followed by the word `open` followed by any path).

Is there a way I can make this work with Deep Link Kit?

**Comment by chrismaddern** [comment]
Hey @jbrennan 

Naming the groups should work:

```
/:component/open/:action
```

Note that this will match:
```
https://thing.com/component/open/action
OR
thing://thing/component/open/action
```

But will not open:
```
thing://component/open/action
```

Since `/` checks everything in the path, excluding the host.

**Comment by jbrennan** [comment]
Wonderful, thanks!
