### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by ehlersd** [button/DeepLinkKit#129]
Any plans for tvOS support?

**Comment by chrismaddern** [comment]
Good question -- we were actually just talking about this the other day.. 

Do you have any sense of the scope of the change?

**Comment by ehlersd** [comment]
I haven't really looked thru your library.  I've used it in a number of iOS app, and now building up some cross-platform tools for iOS/tvOS/watchOS/macOS for a client.  So this was just my first step....

**Comment by ehlersd** [comment]
@chrismaddern I just skimmed thru the code, and it looks like it should be extremely simple (MAYBE as easy as just enabling it in the Podspec file.  I'm going to fork it and try it out...

**Comment by chrismaddern** [comment]
w00t! Pull Requests greatly appreciated :D

**Comment by ehlersd** [comment]
@chrismaddern Done!  No code changes, just a simple update to the Podspec....

**Comment by ehlersd** [comment]
@chrismaddern When you get a chance, if you can push out an new Pod update so I can reference your repo directly in my project (instead of my fork)....

**Comment by wessmith** [comment]
@ehlersd done!
