### ISSUE TITLE
Stops on first route matches even if it doesn't handle it

### ISSUE THREAD

**Issue by glentregoning** [button/DeepLinkKit#131]
Scenario: 
 - I have two DPLRouteHandler's registered for the same URL path (say /mypath)
 - My first route handler returns false for shouldHandleDeepLink if there is a query parameter ( e.g. /mypath?skip_first)
 - In this case I'd like my second DPLRouteHandler to handle this case. 

Issue: 
 - Currently `- [DPLDeepLinkRouter handleURL:(NSURL *)url withCompletion:(DPLRouteCompletionBlock)completionHandler]` stops looking for matches after the first match returns false for shouldHandleDeepLink. 

Ideally it would keep looking in this case until it finds a match which handles the link (or runs out of routes).

**Comment by glentregoning** [comment]
*Bump*

**Comment by wessmith** [comment]
Hi @glentregoning. Thanks for the contribution! Sorry for the delay–I'll take a look tomorrow.
