### ISSUE TITLE
Handling URL's which has URL inside. 

### ISSUE THREAD

**Issue by wixvii** [button/DeepLinkKit#155]
Hey,
We are sending deep link with a URL inside a parameter. 
It looks like : 
"myApp://github.com/webView/https://www.github.com/wixvii"
Here we should get the GitHub link as parameters but can not handle with register function.
it handles like it has more than one parameters because of "/" inside my webView content URL.
Is there any way to fix this problem?
I use "router.register" function with this string: "webview/:url"

**Comment by chrismaddern** [comment]
Hi @wixvii

Unfortunately that’s not a valid url.

The simplest solution is probably to URL encode the destination URL, and then either continue to pass as a path component or send as a query param

**Comment by wixvii** [comment]
I fix this problem with route string "webview/:url(.*)"

**Comment by chrismaddern** [comment]
👍  custom regex matcher for the win then :)
