### ISSUE TITLE
ERROR ITMS-90362 The minimum value is 8.0 for MinimumOSVersion

### ISSUE THREAD

**Issue by uson1x** [button/DeepLinkKit#159]
When submitting builds to App Store, built with `carthage` and Xcode Version 11.2.1 (11B500) toolchain, I get this error in response:

> ERROR ITMS-90362: "Invalid Info.plist value. The value for the key 'MinimumOSVersion' in bundle MeetHubDev.app/Frameworks/DeepLinkKit.framework is invalid. The minimum value is 8.0"

Does it mean that DeepLinkKit.framework's `IPHONEOS_DEPLOYMENT_TARGET` needs to be updated now to 8.0 (like here https://github.com/button/DeepLinkKit/pull/87), rather than 7.1 (set in https://github.com/button/DeepLinkKit/pull/156)?

**Comment by uson1x** [comment]
This PR fixed it for me https://github.com/button/DeepLinkKit/pull/160

**Comment by wessmith** [comment]
Fixed in #160
