### ISSUE TITLE
Is it possible to register route without case-sensitive?

### ISSUE THREAD

**Issue by hendrahalim** [button/DeepLinkKit#162]
I want to register a route without case-sensitive

`router.register("home") { (deeplink) in
     // do some code
  }`

from the code, i expect to accept
scheme://home
scheme://HOME

is there any way to handle this?

**Comment by chrismaddern** [comment]
Currently case insensitive matches aren't supported - the match is run without the [caseInsensitive flag](https://developer.apple.com/documentation/foundation/nsregularexpression/options/1417830-caseinsensitive)

Support could be added somehow here: https://github.com/button/DeepLinkKit/blob/master/DeepLinkKit/Regex/DPLRegularExpression.m#L60

Alternatively, you could match both `home` and `HOME` in the input.
