### ISSUE TITLE
Better type support for Swift

### ISSUE THREAD

**Issue by cjwirth** [button/DeepLinkKit#28]
I was using this in my app, and I was having difficulties with using the subscripting to get/set block route handlers. This is because the subscript method returns `id`, which in Swift was coming up as `AnyObject`. It wasn't let me cast the return value to `DPLRouteHandlerBlock`, because closures aren't objects.

There is probably some elegant solution that I didn't think of, but I just ended up writing a wrapper around it

**Comment by hiltonc** [comment]
You can use `- (void)registerBlock:(DPLRouteHandlerBlock)routeHandlerBlock forRoute:(NSString *)route`.

**Comment by chrismaddern** [comment]
@cjwirth If you have anything that you think could be contribute-able back, would love to see a pull request. Better Swift support is definitely something that we'd like to do soon!

**Comment by basememara** [comment]
Can I see a code sample for this pls? I've been struggling with this and can't get it to work. This is what I have:

AppDelegate:
```
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        self.router = DPLDeepLinkRouter()
        self.router.registerHandlerClass(PostRouteHandler.self, forRoute: "/post/:slug")

        return true
    }
```
PostRouteHandler:
```
public class PostRouteHandler: DPLRouteHandler {
    
    override public func targetViewController() -> UIViewController {
        return PostDetailController()
    }

}
```
PostDetailController:
```
class PostDetailController: UIViewController, DPLTargetViewController {
    func configureWithDeepLink(deepLink: DPLDeepLink!) {
        if let slug = deepLink.routeParameters["slug"] as? String {
            // Do something
        }
    }
}
```
My breakpoint in `configureWithDeepLink` just won't hit when going to `mydpl://post/my-slug`.

**Comment by platedbay** [comment]
You don't need the first /
```
self.router.registerHandlerClass(PostRouteHandler.self, forRoute: "post/:slug")
```

**Comment by chrismaddern** [comment]
Anything after the first `/` in an incoming URL is considered part of the path, in this case, `post` is actually the host... just another way that URLs aren't perfectly designed for deep linking ;)

@platedbay is right.. remove the first `/` and you should be good.

**Comment by basememara** [comment]
Ahh silly mistake, it worked! I copied the samples `/product/:sku` route but I guess that wasn't what I thought. Thanks! I hope the sample helps someone else ;)
